# Generated by Django 2.2 on 2019-04-07 14:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='content2',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[1, 2, 3, 4, 5, 6], max_length=606, size=6),
            preserve_default=False,
        ),
    ]
