# Generated by Django 2.2 on 2019-04-07 14:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0002_list_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content2',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=5000, size=None),
        ),
    ]
