# Generated by Django 2.2 on 2019-04-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0003_auto_20190407_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='content2',
            new_name='viewers',
        ),
    ]
