# Generated by Django 2.2 on 2019-04-08 00:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0004_auto_20190407_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(default='Base description', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='viewers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), help_text='Enter the usernames of the users that will have access to your list (separated with commas)', max_length=5000, size=None),
        ),
    ]
