# Generated by Django 2.2 on 2019-04-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0005_auto_20190407_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(help_text='Add a short description of your list', max_length=5000),
        ),
    ]
