# Generated by Django 2.2 on 2019-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0007_auto_20190407_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('links', models.TextField()),
                ('images', models.TextField()),
            ],
        ),
    ]
