# Generated by Django 2.2 on 2019-04-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0008_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
