# Generated by Django 2.2 on 2019-04-09 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listApp', '0009_delete_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('links', models.TextField(blank=True, help_text='[Optional] Add one or more useful links (separated with commas)')),
                ('images', models.TextField(blank=True, help_text='[Optional] Enter the URLs of one or more images (separated with commas)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listApp.List')),
            ],
        ),
    ]
