# Generated by Django 2.2 on 2019-04-09 23:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0010_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='images',
            field=models.TextField(blank=True, help_text='[Optional] Enter the URLs of one or more images (separated with semicolons)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='links',
            field=models.TextField(blank=True, help_text='[Optional] Add one or more useful links (separated with semicolons)'),
        ),
        migrations.AlterField(
            model_name='list',
            name='viewers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, help_text='Enter the usernames of the users that will have access to your list (separated with semicolons)', max_length=5000, size=None),
        ),
    ]
