# Generated by Django 2.2 on 2019-04-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0011_auto_20190409_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='content',
        ),
    ]
