# Generated by Django 2.2 on 2019-04-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0012_remove_list_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.CharField(help_text='Enter the username or the email adress of the user that you want to share your list with', max_length=500)),
                ('theList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listApp.List')),
            ],
        ),
    ]
